### PR TITLE
Ensure flake8-quotes in all projects.

### PR DESCRIPTION
**Pull request by harikishen**
@garbas i've done the changes required for flake8-quotes.

### CODE REVIEW

**Comment by garbas** [comment]
2017-06-09-122052_464x358_scrot

Here is the list (the ones in red) of project which fails. And here is the link to taskcluster for this build
https://tools.taskcluster.net/task-group-inspector/#/UAHmsVuXRKukT0xJuN33MA/daCeqaYfQWmFeEP_IQmVRg?_k=ebmanb

You can also inspect the output of the build and see why it fails.

**Comment by harikishen** [comment]
@garbas i checked and tried rebuilding again. I don't get the failures locally.

**Comment by garbas** [comment]
I can also see the errors locally eg. for releng-tooltool

```console
% nix-build nix/default.nix -A releng-tooltool
...
################################################################
## flake8 ######################################################
################################################################
./releng_tooltool/models.py:37:44: Q000 Remove bad quotes.
./releng_tooltool/models.py:120:40: Q000 Remove bad quotes.
./releng_tooltool/models.py:136:32: Q000 Remove bad quotes.
./releng_tooltool/models.py:136:48: Q000 Remove bad quotes.
./releng_tooltool/models.py:142:33: Q000 Remove bad quotes.
./releng_tooltool/models.py:142:50: Q000 Remove bad quotes.
./releng_tooltool/models.py:170:40: Q000 Remove bad quotes.
./releng_tooltool/aws.py:56:32: Q000 Remove bad quotes.
./releng_tooltool/aws.py:82:32: Q000 Remove bad quotes.
./releng_tooltool/aws.py:101:13: Q000 Remove bad quotes.
./releng_tooltool/aws.py:106:17: Q000 Remove bad quotes.
./releng_tooltool/aws.py:119:38: Q000 Remove bad quotes.
./releng_tooltool/aws.py:131:22: Q000 Remove bad quotes.
./releng_tooltool/api.py:49:13: Q000 Remove bad quotes.
./releng_tooltool/api.py:54:13: Q000 Remove bad quotes.
./releng_tooltool/api.py:59:13: Q000 Remove bad quotes.
./releng_tooltool/api.py:101:17: Q000 Remove bad quotes.
./releng_tooltool/api.py:112:21: Q000 Remove bad quotes.
./releng_tooltool/api.py:122:17: Q000 Remove bad quotes.
./releng_tooltool/api.py:123:17: Q000 Remove bad quotes.
./releng_tooltool/api.py:168:46: Q000 Remove bad quotes.
./releng_tooltool/api.py:205:46: Q000 Remove bad quotes.
./releng_tooltool/api.py:236:14: Q000 Remove bad quotes.
./releng_tooltool/api.py:252:50: Q000 Remove bad quotes.
./releng_tooltool/api.py:263:54: Q000 Remove bad quotes.
./releng_tooltool/api.py:266:50: Q000 Remove bad quotes.
```

**Comment by harikishen** [comment]
how do i make a clean rebuild ?

**Comment by garbas** [comment]
hopefully with my last commit we can merge this (if taskcluster builds) so that this PR wont get stalled.

**Comment by harikishen** [comment]
@garbas thanks for completing the rest of the files. I'll be back by 14th or 15th.

**Pull request merged**
