### PR TITLE
shipit: Add rationale about pipelines

### PR DESCRIPTION
**Pull request by JohanLorenzo**
@rail @garbas @lundjordan and I discussed if we're heading towards reimplementing TC's queue. Here is an attempt to explain the differences between pipelines and queues. What do you think @catlee ? r?

### CODE REVIEW

**Comment by lundjordan** [comment]
Thanks for writing docs! I think it is important to compare queues to pipelines and steps to workers. Particularly with the pipeline<->step interaction and its generic API implementation.

It is great to have this written down in docs so we can weigh the following options:

1) use solely taskcluster queue for our pipeline and taskcluster workers for our steps by fixing 5day deadlines in current production tc queue or standing up a releng specific tc queue.

2) implement our own pipeline and steps that mirror the behavior of taskcluster to get around limitations. A step itself might internally delegate tasks to taskcluster (a taskcluster step service) but externally it adheres to shipit's pipeline API.

3) discussed more today, we have a merge of (1) or (2). We could continue to have our own pipeline but the steps each represent a taskcluster graph that has been submitted to tc (including sign off tasks). This pipeline could be a sequential list that only cares when the previous step (tc graph) is complete. Thus simplifying the pipeline (queue) resolution, delegating the || task mgmt to taskcluster queue and only caring if a pipeline step is complete or incomplete.

Really this boils down to if we can use a taskcluster queue without a 5 day limit and how much we want to offer a solution that is generic and not dependent on taskcluster at all.

As an aside, it's great that we have a working type that is basically option (1) and can be continued on if we decide to proceed as is. Thanks @garbas for showing off a lot of cool tech this week and designing an impressive product. I'm really looking forward to shipit v2 now.

**Comment by lundjordan** [comment]
ftr: here is a terrible sketch of option (3) we discussed today: https://people-mozilla.org/~jlund/IMG_0575.jpg

**Comment by lundjordan** [comment]
I personally think it would be really neat if we could reuse taskcluster. Both the queue and workers. 

Workers are generic enough that we could implement our own 'signoff', 'bugzilla', 'jenkins', 'travis', etc types that communicate with those services and thus allow integration for future products that don't yet use taskcluster. If the only thing blocking us from doing that is a 5 day deadline, that's kind a crummy :)

**Comment by garbas** [comment]
@JohanLorenzo @lundjordan would it be ok to close this ticket. I assume once we will have a clear idea what we are building we will document it.

**Comment by lundjordan** [comment]
Works for me. We can add and modify these docs when we have a clear path forward :)

**Pull request closed without merging**
