### PR TITLE
Docker build integration w/ Taskcluster

### PR DESCRIPTION
**Pull request by mozbhearsum**
This is for #220. I've tested out the Makefile locally a bit by faking out the URL and making sure the parsing works, but I'm not sure to do full end to end testing. This is very similar to what we do for Balrog though, so it *should* work. This is built on top of #207.

### CODE REVIEW

**Comment by garbas** [comment]
I think I told you that this is exactly what is being in the works this week.

A lot of things here will change, I will make sure that with the new setup the also docker images get build and pushed.

**Comment by mozbhearsum** [comment]
Is there an ETA for that? I don't want to maintain an image on my personal Dockerhub account.

**Comment by garbas** [comment]
This week. Would that be ok for you?

**Comment by mozbhearsum** [comment]
Yup! That's fine.

**Pull request closed without merging**
