### PR TITLE
shipit-risk-assessment: Remove project

### PR DESCRIPTION
**Pull request by La0**

### CODE REVIEW

**Comment by marco-c** [comment]
The project is not being used and doesn't contain any code that we can salvage. We might pick it up again at some point, but so many things have changed in the meantime that I think it's better to restart the project from scratch.

**Comment by La0** [comment]
It was not deployed since a few months...

**Comment by marco-c** [comment]
The exception in the static analysis build is an issue with s3 (which has been happening pretty often lately).
There are conflicts to resolve before this can be merged.

**Comment by garbas** [comment]
I added a space to the Title to re-trigger the build. @marco-c I guess another bug in taskcluster :) or a feature depends how you look at it

**Comment by marco-c** [comment]
It's happening again. I'll retrigger the build again via the "space hack".

**Pull request merged**
