### PR TITLE
[WIP] shipit_taskcluster: Support continuation queries with listTaskGroup

### PR DESCRIPTION
**Pull request by srfraser**
IMPORTANT: This PR won't work until https://github.com/taskcluster/taskcluster-client.py/pull/76 has been merged and a new taskcluster-client.py released. Until we're on that version, here is a PR to store the changes needed to make things work properly.

### CODE REVIEW

**Comment by garbas** [comment]
@srfraser with nix you don't have to wait :)

can you confirm this works for you?

**Comment by srfraser** [comment]
I can't test with nix due to missing secrets. It doesn't pick them up from the environment.

Is it safe to refer to a PR in an environment that'll end up in production? That makes me nervous. We'd end up supporting a PR if they refuse the change.

**Comment by garbas** [comment]
for now just hardcore ``BALROG_*`` secrets in ``settings.py`` I have a solution in the working which will solve this and also other issues, but I need a day to fix it. 

It is safe, since we check for the ``sha256``, if it changes the build will fail. This unblocks us for now and we can revisit the patch once we have the answer from taskcluster team. In any way, we would need to at least get a proposal for a better solution from them and then we change it.

**Comment by srfraser** [comment]
It's complaining about`DATABASE_URL` and `TASKCLUSTER_ACCESS_TOKEN`, which should already be covered. Will investigate.

**Comment by garbas** [comment]
with work going on shipit-workflow i think this can be closed

**Pull request closed without merging**
