### PR TITLE
Removed windows clang builds, which don't appear to work

### PR DESCRIPTION
**Pull request by alex**
Example failure: https://treeherder.mozilla.org/logviewer.html#?job_id=93804902&repo=try&lineNumber=662

cc: @garbas

### CODE REVIEW

**Comment by garbas** [comment]
@alex Since you weren't 100% about this change I asked in #sheriffs channel if anybody would object this. If nothing this will be merged and deployed with next regular weekly release ( #277 ).

**Comment by alex** [comment]
Sounds great, thanks!

**Comment by philor** [comment]
You probably didn't get much of an answer out of #sheriffs, but those were the original names for what's now win(32/64)-st-an, renamed in [bug 1325723](https://bugzilla.mozilla.org/show_bug.cgi?id=1325723), and then the new names were added in [bug 1325719](https://bugzilla.mozilla.org/show_bug.cgi?id=1325719) without removing the old names.

**Comment by garbas** [comment]
@philor thank you! I will move ahead and merge this

**Pull request merged**
