### PR TITLE
adds docker support for please cmd

### PR DESCRIPTION
**Pull request by lundjordan**

### CODE REVIEW

**Comment by lundjordan** [comment]
@srfraser would you mind trying this out from macOS? This is needed for me to use shipit-* services from docker+nix

@mozbhearsum would you mind trying this from linux?

$ ./please run postgresql
$ ./please run shipit-taskcluster   # or shipit-signoff

**Comment by lundjordan** [comment]
@garbas this uses latest-tmp image. could you append the cset that made this image to this PR (I've allowed edits from maintainers).

Then, once ben and simon confirm it works for both linux and mac, could you push this to base-latest when you do your next deploy?

:)

**Comment by mozbhearsum** [comment]
Worked for me.

**Comment by mozbhearsum** [comment]
One thing I noticed just now is that ^C doesn't appear to stop the container. Not a blocker, but mildly annoying.

**Comment by garbas** [comment]
@mozbhearsum currently you will have to manually stop container via ``docker stop mozilla-releng-services``. This is the best solution we could come up right now, but it would be nice to stop it after eg. Xmin of inactivity.

**Comment by mozbhearsum** [comment]
Perhaps it could be run in interactive mode? IIRC, ^C will stop containers that are running in the foreground.

**Comment by garbas** [comment]
@mozbhearsum ``./please`` command will always run in the same (names) container, so that nix files dont get redownloded everytime. also we only use ``docker run`` to create and start the (named) container. then ``docker exec`` is used to run the command inside container.

**Pull request merged**
