### PR TITLE
shipit-static-analysis: Slightly improve automated code review feedback.

### PR DESCRIPTION
**Pull request by jankeromnes**

### CODE REVIEW

**Comment by jankeromnes** [comment]
@La0 please have a look whenever you have some time (not urgent). 😃

**Comment by La0** [comment]
@jankeromnes The build failed, you need to update the unit tests.
Can you also rebase on top of master so that the build will use the new base image v32 ?

**Comment by jankeromnes** [comment]
> The build failed, you need to update the unit tests.

Indeed. This should fix it.

> Can you also rebase on top of master so that the build will use the new base image v32 ?

Rebased on top of `origin/master`.

**Comment by jankeromnes** [comment]
Thanks for approving and merging this!

**Pull request merged**
