### PR TITLE
nix: Add setup script

### PR DESCRIPTION
**Pull request by La0**
Tested on a clean install of Ubuntu 16.04

### CODE REVIEW

**Comment by garbas** [comment]
could you rerun this script on a computer that already has nix installed with this script?
we also need to make sure that this script can upgrade from single user installation to multiuser installation.

**Comment by La0** [comment]
Expected behavior:
1. if nix installation is single user, then it would upgrade the nix installation to multiuser
2. if there is already an existing multi user installation then it should just update nix via nix-env

**Comment by mozbhearsum** [comment]
I gave this a try on Ubuntu 16.10. I need to run it again because of S3 issue, but one thing I noticed is that check_dep failed for groupadd and useradd, presumably because they're not in $PATH for non-root users.

**Comment by mozbhearsum** [comment]
I seem to be getting a consistent error in step 9, too:
> 9. Set up the user profile
> uninstalling ‘nixpkgs-17.09pre102292.3fc79cb’
> error: cannot connect to daemon at ‘/nix/var/nix/daemon-socket/socket’: No such file or directory

I'm guessing that nix-daemon didn't start in step 6...

**Comment by La0** [comment]
@mozbhearsum I just tried the setup script on a fresh install of Ubuntu 16.10: it works as expected (groupadd & useradd are in my user path, the daemon runs fine). 
Could you try to re-run it, and send me the full shell output through pastebin ?

**Comment by La0** [comment]
@garbas I updated the script to support existing single user & mutli user setups.

**Comment by mozbhearsum** [comment]
For the record, I'm no longer trying to use nix for local development (I'm using the Docker work from #207 instead), but I gave this a quick try. I still get an immediate failure because groupadd is not in $PATH, but let's assume that's just something funky on my local system if that's not an issue for you on a clean Ubuntu 16.10.

After changing $PATH, I get:
```
➜  mozilla-relengapi git:(189-setup-script) bash nix/setup.sh 
Testing sudo access
Detected init service: systemd
1. Installing Nix as single user mode
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2354  100  2354    0     0   2837      0 --:--:-- --:--:-- --:--:--  2836
downloading Nix 1.11.7 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-1.11.7/nix-1.11.7-x86_64-linux.tar.bz2' to '/tmp/nix-binary-tarball-unpack.nLpTX9DBiE'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.4M  100 27.4M    0     0  1296k      0  0:00:21  0:00:21 --:--:-- 1106k
performing a single-user installation of Nix...
copying Nix to /nix/store...............................
initialising Nix database...
installing ‘nix-1.11.7’
building path(s) ‘/nix/store/w54ghq1yhfiichqjinabhbw91bbssb59-user-environment’
error: setting uid: Operation not permitted
error: cannot kill processes for uid ‘999’: failed with exit code 1
/tmp/nix-binary-tarball-unpack.nLpTX9DBiE/unpack/nix-1.11.7-x86_64-linux/install: unable to install Nix into your default profile
```

**Comment by garbas** [comment]
done with https://github.com/mozilla-releng/services/commit/ab6742da3c3df5cceb5cc232a2e166b1dfa6522c

**Pull request closed without merging**
