### PR TITLE
Remove utils.mkdir and use os.makedirs instead

### LINKED ISSUE #956: Remove utils.mkdir and use makedirs everywhere
Since Python 3.2, there's a `exist_ok` parameter that allows to ignore errors due to an already existing directory. So, we can drop utils.mkdir and use makedirs with exist_ok=True everywhere.

### PR DESCRIPTION
**Pull request by fiennyangeln**
Fixes #956.

### CODE REVIEW

**Comment by marco-c** [comment]
Thanks for the PR, @fiennyangeln!

There are a couple of changes to make:
1) The build is failing, you can see the logs if you click on "Details" on the right of "Taskcluster". You can reproduce the failure locally by running `./please check shipit-code-coverage`.
2) We should remove the `mkdir` function from cli_common.utils too.

**Comment by fiennyangeln** [comment]
@marco-c Thanks for the review:D updated!

**Comment by marco-c** [comment]
Hey @fiennyangeln, point 2 is still missing:
> We should remove the mkdir function from cli_common.utils too.

**Comment by marco-c** [comment]
The code is in lib/cli_common/cli_common/utils.py. You will need to remove the test too

**Comment by fiennyangeln** [comment]
@marco-c thanks for reminding.. Removed!

**Comment by marco-c** [comment]
Thanks! The only failure is a transient one (s3 upload).

**Pull request merged**
