### PR TITLE
Fix updateFromGithub update script

### PR DESCRIPTION
**Pull request by seppeljordan**
With current nixpkgs-unstable the updateFromGithub update script seems broken.  This should fix it

### CODE REVIEW

**Comment by garbas** [comment]
@seppeljordan wow, thank you! I'm actually planning to work on this next week. you can probably see that an old nixpkgs revision is used (``nix/nixpkgs.json``) and next week we are going to update it.

**Comment by seppeljordan** [comment]
feel free to merge if/when you want.  i am currently working with a fork currently anyway because i am only using updateFromGithub anyway.

**Comment by garbas** [comment]
@seppeljordan maybe we should consider moving this function to`` nixpkgs``

**Comment by garbas** [comment]
this is already part of ``update`` branch and will soon land in master.

@seppeljordan tnx!

**Pull request closed without merging**
